/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5_sergiosuazo;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Sergio
 */
public class Clash_Royale extends javax.swing.JFrame {

    static ArrayList<Usuario> users=new ArrayList();
    static ArrayList<Clan> clan=new ArrayList();
    static Usuario usuario_actual;
    static boolean login=false;
    static boolean tiene_clan=false;
    static Carta carta_agregar;
    /**
     * Creates new form Clash_Royale
     */
    public Clash_Royale() {
        initComponents();
        tp_tabs.setEnabled(login);
        tp_tabs.setEnabledAt(1, true);
        //usuario de prueba
        Usuario n=new Usuario("sergio","suazo","sergios1001","12345",21,Color.BLUE,new Date());
        users.add(n);
        usuario_actual=n;
        ArrayList<Mazo> mazo=new ArrayList();
        ArrayList<Carta> m1=new ArrayList();
        ArrayList<Carta> m2=new ArrayList();
        ArrayList<Carta> m3=new ArrayList();  
        mazo.add(new Mazo());
        mazo.add(new Mazo());
        mazo.add(new Mazo());
        ((Mazo)mazo.get(0)).setCarta(m1);
        ((Mazo)mazo.get(1)).setCarta(m2);
        ((Mazo)mazo.get(2)).setCarta(m3);
        usuario_actual.setMazo(mazo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NuevoUser = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tf_nombreN = new javax.swing.JTextField();
        tf_apellido = new javax.swing.JTextField();
        tf_userN = new javax.swing.JTextField();
        tf_contraN = new javax.swing.JTextField();
        jd_fecha = new com.toedter.calendar.JDateChooser();
        bt_color = new javax.swing.JButton();
        bt_adduser = new javax.swing.JButton();
        NuevoClan = new javax.swing.JDialog();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tf_nombreClan = new javax.swing.JTextField();
        cb_tipo = new javax.swing.JComboBox<>();
        jd_fechaCreacion = new com.toedter.calendar.JDateChooser();
        bt_addClan = new javax.swing.JButton();
        tp_tabs = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_usuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bt_ingresar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bt_crear = new javax.swing.JButton();
        pf_password = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cb_carta = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bt_adicionar = new javax.swing.JButton();
        sp_dano = new javax.swing.JSpinner();
        sp_vida = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_mazos = new javax.swing.JTree();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_nombrecarta = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        sp_mazo = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_clan = new javax.swing.JList<>();
        bt_join = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        bt_newClan = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jl_miembros = new javax.swing.JList<>();

        NuevoUser.setTitle("Nuevo Usuario");

        jLabel10.setText("Nombre");

        jLabel11.setText("Usuario");

        jLabel12.setText("Contraseña");

        jLabel13.setText("Fecha de Nacimiento");

        jLabel14.setText("Color favorito");

        jLabel15.setText("Apellido");

        bt_color.setBackground(new java.awt.Color(255, 0, 0));

        bt_adduser.setText("Crear Usuario");
        bt_adduser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_adduserMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout NuevoUserLayout = new javax.swing.GroupLayout(NuevoUser.getContentPane());
        NuevoUser.getContentPane().setLayout(NuevoUserLayout);
        NuevoUserLayout.setHorizontalGroup(
            NuevoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NuevoUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NuevoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NuevoUserLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(41, 41, 41)
                        .addComponent(bt_color, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NuevoUserLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(97, 97, 97)
                        .addComponent(tf_nombreN, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NuevoUserLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(97, 97, 97)
                        .addComponent(tf_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NuevoUserLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(23, 23, 23)
                        .addComponent(jd_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NuevoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bt_adduser, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(NuevoUserLayout.createSequentialGroup()
                            .addGroup(NuevoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(jLabel11))
                            .addGap(77, 77, 77)
                            .addGroup(NuevoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_userN)
                                .addComponent(tf_contraN, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)))))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        NuevoUserLayout.setVerticalGroup(
            NuevoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NuevoUserLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(NuevoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(NuevoUserLayout.createSequentialGroup()
                        .addGroup(NuevoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tf_nombreN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(NuevoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(tf_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12))
                    .addGroup(NuevoUserLayout.createSequentialGroup()
                        .addComponent(tf_userN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_contraN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(NuevoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jd_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(NuevoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_color, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(NuevoUserLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel14)))
                .addGap(39, 39, 39)
                .addComponent(bt_adduser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        NuevoClan.setTitle("Nuevo Clan");

        jLabel20.setText("Nombre: ");

        jLabel21.setText("Tipo: ");

        jLabel22.setText("Fecha: ");

        cb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bronze", "Plata", "Oro", "Legendario" }));
        cb_tipo.setToolTipText("");

        bt_addClan.setText("Crear Clan");
        bt_addClan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_addClanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout NuevoClanLayout = new javax.swing.GroupLayout(NuevoClan.getContentPane());
        NuevoClan.getContentPane().setLayout(NuevoClanLayout);
        NuevoClanLayout.setHorizontalGroup(
            NuevoClanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NuevoClanLayout.createSequentialGroup()
                .addGroup(NuevoClanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NuevoClanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(NuevoClanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addGroup(NuevoClanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_nombreClan, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jd_fechaCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(NuevoClanLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(bt_addClan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        NuevoClanLayout.setVerticalGroup(
            NuevoClanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NuevoClanLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(NuevoClanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addComponent(tf_nombreClan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(NuevoClanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(NuevoClanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22)
                    .addComponent(jd_fechaCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(bt_addClan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Usuario");

        jLabel2.setText("Contraseña");

        bt_ingresar.setText("Ingresar");
        bt_ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_ingresarMouseClicked(evt);
            }
        });

        jLabel3.setText("No tiene usuario? Cree uno aqui:");

        bt_crear.setText("Crear Usuario");
        bt_crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(bt_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_usuario)
                            .addComponent(pf_password, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(bt_crear, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(pf_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(bt_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(bt_crear, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        tp_tabs.addTab("Login", jPanel1);

        jLabel4.setText("Seleccione una Carta: ");

        cb_carta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Minipekka", "Montapuerco", "Leñador", "Dragon Infernal", "Golem", "Dragon", "Gigante Noble", "Pandilla de Duendes" }));

        jLabel5.setText("Daño de la Carta: ");

        jLabel6.setText("Puntos de Vida: ");

        bt_adicionar.setText("Adicionar a mi Mazo");
        bt_adicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_adicionarMouseClicked(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Mazos");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Mazo1");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Mazo2");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Mazo3");
        treeNode1.add(treeNode2);
        jt_mazos.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jt_mazos);

        jLabel7.setText("Mis Mazos");

        jLabel8.setText("Nombre: ");

        jLabel9.setText("Asignar al Mazo: ");

        sp_mazo.setModel(new javax.swing.SpinnerNumberModel(0, 0, 2, 1));
        sp_mazo.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_carta, 0, 166, Short.MAX_VALUE)
                            .addComponent(tf_nombrecarta)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(bt_adicionar))
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sp_dano)
                            .addComponent(sp_vida)
                            .addComponent(sp_mazo, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cb_carta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tf_nombrecarta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(sp_dano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(sp_vida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(bt_adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(sp_mazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(105, 105, 105))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        tp_tabs.addTab("Crear Carta", jPanel2);

        jLabel16.setText("Lista de Clanes: ");

        jScrollPane2.setViewportView(jl_clan);

        bt_join.setText("Unirse al Clan");

        jLabel17.setText("Quieres crear tu propio clan? Hazlo aqui:");

        bt_newClan.setText("Crear Clan");
        bt_newClan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_newClanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(bt_join, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel17)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(bt_newClan, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(bt_join, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(jLabel17)
                .addGap(37, 37, 37)
                .addComponent(bt_newClan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        tp_tabs.addTab("Unirse a un Clan", jPanel4);

        jScrollPane3.setViewportView(jTextPane1);

        jLabel18.setText("Clan: ");

        jLabel19.setText("Miembros: ");

        jScrollPane4.setViewportView(jl_miembros);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel19)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(413, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        tp_tabs.addTab("Mi Clan", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tp_tabs)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tp_tabs)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_ingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_ingresarMouseClicked
        // TODO add your handling code here:
        String usuario,contra;
        usuario=tf_usuario.getText();
        contra=pf_password.getText();
        int pos=0;
        for (int i = 0; i < users.size(); i++) {
            if(users.get(i).getUsername().equals(usuario) && users.get(i).getContra().equals(contra))
            {
                login=true;
                pos=i;
                break;
            }
            else
            {
                login=false;
                System.out.println(users.get(i).getUsername());
                System.out.println(users.get(i).getContra());
                System.out.println(usuario);
                System.out.println(contra);
            } 
        }
        if(login)
        {
            JOptionPane.showMessageDialog(this,"Bienvenido " +usuario);
            usuario_actual=users.get(pos);
            tp_tabs.setEnabled(login);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Error, el usuario o la contrasena es incorrecta");
            tp_tabs.setEnabled(login);
        }

    }//GEN-LAST:event_bt_ingresarMouseClicked

    private void bt_crearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearMouseClicked
        // TODO add your handling code here:
        NuevoUser.pack();
        NuevoUser.setVisible(true);
    }//GEN-LAST:event_bt_crearMouseClicked

    private void bt_adduserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_adduserMouseClicked
        // TODO add your handling code here:
        String nombre, apellido,usuario,contra;
        Color color;
        Date fecha;
        long diferencia;
        int edad;
        
        nombre=tf_nombreN.getText();
        apellido=tf_apellido.getText();
        usuario=tf_userN.getText();
        contra=tf_contraN.getText();
        fecha=jd_fecha.getDate();
        diferencia=new Date().getTime()-fecha.getTime();
        edad=(int)(diferencia/(60*60*1000*24))/365;
        color=bt_color.getBackground();
        Usuario u=new Usuario(nombre,apellido,usuario,contra,edad,color,fecha);
        users.add(u);
        ArrayList<Mazo> mazo=new ArrayList();
        ArrayList<Carta> m1=new ArrayList();
        ArrayList<Carta> m2=new ArrayList();
        ArrayList<Carta> m3=new ArrayList();  
        mazo.add(new Mazo());
        ((Mazo)mazo.get(0)).setCarta(m1);
        ((Mazo)mazo.get(1)).setCarta(m2);
        ((Mazo)mazo.get(2)).setCarta(m3);
        usuario_actual.setMazo(mazo);
        JOptionPane.showMessageDialog(this, "Se agrego el usuario con exito");
        NuevoUser.setVisible(false);
        tf_nombreN.setText("");
        tf_apellido.setText("");
        tf_userN.setText("");
        tf_contraN.setText("");
        jd_fecha.setDate(new Date());
        bt_color.setBackground(Color.red);
    }//GEN-LAST:event_bt_adduserMouseClicked

    private void bt_adicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_adicionarMouseClicked
        // TODO add your handling code here:
        String nombre, estilo,tipo="";
        int daño,vida,mazo;
        
        estilo=cb_carta.getSelectedItem().toString();
        nombre=tf_nombrecarta.getText();
        daño=(Integer)sp_dano.getValue();
        vida=(Integer)sp_vida.getValue();
        mazo=(Integer)sp_mazo.getValue();
        DefaultTreeModel modeloArbol = (DefaultTreeModel)jt_mazos.getModel();
        DefaultMutableTreeNode raiz= (DefaultMutableTreeNode) modeloArbol.getRoot();
        
        if(estilo.equals("Minipekka"))
        {
            Minipekka m=new Minipekka("Alta", "Especial", "Terrestres", 4, nombre, daño, vida);
            usuario_actual.getMazo().get(mazo).getCarta().add(m);
            tipo="Especial";
            carta_agregar=m;
        }
        if(estilo.equals("Montapuerco"))
        {
            Montapuerco m=new Montapuerco("Alta", "Especial", "Terrestres", 4, nombre, daño, vida);
            usuario_actual.getMazo().get(mazo).getCarta().add(m);
            tipo="Especial";
            carta_agregar=m;
        }
        if(estilo.equals("Leñador"))
        {
            Leñador m=new Leñador("Alta", "Legendaria", "Terrestres", 4, nombre, daño, vida);
            usuario_actual.getMazo().get(mazo).getCarta().add(m);
            tipo="Legendaria";
            carta_agregar=m;
        }
        if(estilo.equals("Dragon Infernal"))
        {
            Dragon_infernal m=new Dragon_infernal("Media", "Legendaria", "Aereos", 4, nombre, daño, vida);
            usuario_actual.getMazo().get(mazo).getCarta().add(m);
            tipo="Legendaria";
            carta_agregar=m;
        }
        if(estilo.equals("Golem"))
        {
            Golem m=new Golem("Baja", "Epica", "Terrestres", 8, nombre, daño, vida);
            usuario_actual.getMazo().get(mazo).getCarta().add(m);
            tipo="Epica";
            carta_agregar=m;
        }
        if(estilo.equals("Dragon"))
        {
            Dragon m=new Dragon("Media", "Epica", "Aereos", 4, nombre, daño, vida);
            usuario_actual.getMazo().get(mazo).getCarta().add(m);
            tipo="Epica";
            carta_agregar=m;
        }
        if(estilo.equals("Gigante Noble"))
        {
            Gigante_Noble m=new Gigante_Noble("Media", "Comun", "Terrestres", 6, nombre, daño, vida);
            usuario_actual.getMazo().get(mazo).getCarta().add(m);
            tipo="Comun";
            carta_agregar=m;
        }
        if(estilo.equals("Pandilla de Duandes"))
        {
            Pandilla_Duendes m=new Pandilla_Duendes("Alta", "Comun", "Aereos", 4, nombre, daño, vida);
            usuario_actual.getMazo().get(mazo).getCarta().add(m);
            tipo="Comun";
            carta_agregar=m;
        }
        int size=usuario_actual.getMazo().get(mazo).getCarta().size();
        boolean flag=true;
        if(size>3)
        {
            flag=false;
        }
        int centinela=-1;
        for (int i = 0; i < raiz.getChildAt(mazo).getChildCount(); i++) 
        {
            if(raiz.getChildAt(mazo).getChildAt(i).equals(tipo)&&flag)
            {
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Carta(nombre,daño,vida));
                ((DefaultMutableTreeNode) raiz.getChildAt(mazo).getChildAt(i)).add(p);
                centinela=1;
            }
        }
        if(centinela==-1&&flag)
            {
                DefaultMutableTreeNode n = new DefaultMutableTreeNode(tipo);
                DefaultMutableTreeNode p= new DefaultMutableTreeNode(new Carta(nombre,daño,vida));
                n.add(p);
                ((DefaultMutableTreeNode)raiz.getChildAt(mazo)).add(n);
            }
        else
        {
            JOptionPane.showMessageDialog(this, "Ya no se pueden agregar cartas a este mazo");
        }
            modeloArbol.reload();
    }//GEN-LAST:event_bt_adicionarMouseClicked

    private void bt_newClanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_newClanMouseClicked
        // TODO add your handling code here:
        if(tiene_clan)
        {
            JOptionPane.showMessageDialog(this, "El usuario ya es parte de un clan");
        }
        else
        {
            
            NuevoClan.pack();
            NuevoClan.setVisible(true); 
            
        }
    }//GEN-LAST:event_bt_newClanMouseClicked

    private void bt_addClanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_addClanMouseClicked
        // TODO add your handling code here:
        String nombre,tipo,lider;
        Date fecha;
        nombre=tf_nombreClan.getText();
        tipo=cb_tipo.getSelectedItem().toString();
        fecha=jd_fechaCreacion.getDate();
        lider=usuario_actual.getNombre();
        Clan c=new Clan(nombre,tipo,lider,fecha);
        clan.add(c);
        ArrayList<Usuario> miembros=new ArrayList();
        miembros.add(usuario_actual);
        c.setMiembros(miembros);
        JOptionPane.showMessageDialog(this, "Se creo el Clan con exito");
        NuevoClan.setVisible(false);
        tf_nombreClan.setText("");
        cb_tipo.setSelectedItem(0);
        jd_fechaCreacion.setDate(new Date());
        tiene_clan=true;
        
    }//GEN-LAST:event_bt_addClanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clash_Royale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clash_Royale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clash_Royale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clash_Royale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clash_Royale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog NuevoClan;
    private javax.swing.JDialog NuevoUser;
    private javax.swing.JButton bt_addClan;
    private javax.swing.JButton bt_adduser;
    private javax.swing.JButton bt_adicionar;
    private javax.swing.JButton bt_color;
    private javax.swing.JButton bt_crear;
    private javax.swing.JButton bt_ingresar;
    private javax.swing.JButton bt_join;
    private javax.swing.JButton bt_newClan;
    private javax.swing.JComboBox<String> cb_carta;
    private javax.swing.JComboBox<String> cb_tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane jTextPane1;
    private com.toedter.calendar.JDateChooser jd_fecha;
    private com.toedter.calendar.JDateChooser jd_fechaCreacion;
    private javax.swing.JList<String> jl_clan;
    private javax.swing.JList<String> jl_miembros;
    private javax.swing.JTree jt_mazos;
    private javax.swing.JPasswordField pf_password;
    private javax.swing.JSpinner sp_dano;
    private javax.swing.JSpinner sp_mazo;
    private javax.swing.JSpinner sp_vida;
    private javax.swing.JTextField tf_apellido;
    private javax.swing.JTextField tf_contraN;
    private javax.swing.JTextField tf_nombreClan;
    private javax.swing.JTextField tf_nombreN;
    private javax.swing.JTextField tf_nombrecarta;
    private javax.swing.JTextField tf_userN;
    private javax.swing.JTextField tf_usuario;
    private javax.swing.JTabbedPane tp_tabs;
    // End of variables declaration//GEN-END:variables
}
